"""Generates (or removes) synthetic Feature/Journal records for stress-testing
the bulk-fetch performance work (see common/js/lib/content-fetch.js's own
fetchKindEntriesWithIds/fetchKindEntriesForSystem and server/storage.py's
get_items_bulk).

Inserts directly via save_item() — the exact same function the real
POST /content/{bucket}/{id} route uses — rather than driving thousands of
individual HTTP requests, which would make seeding itself the bottleneck.
Every synthetic id is prefixed `feat.stress-`/`journal_stress-` so it's
trivially identifiable and never collides with real content; --cleanup
removes everything under those prefixes and nothing else.

Run from the repo root (same convention as the server itself):
    python server/scripts/stress_seed.py --kind feature --count 2000
    python server/scripts/stress_seed.py --kind journal --count 500
    python server/scripts/stress_seed.py --kind feature --count 2000 --cleanup
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Repo-root-relative absolute imports (server/__init__.py makes `server` a
# real package) — inserted defensively so this also works when run as a
# plain script (`python server/scripts/stress_seed.py`), not just via
# `python -m server.scripts.stress_seed`.
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from server.auth import ensure_default_admin, get_user_by_username  # noqa: E402
from server.config import ConfigLoader  # noqa: E402
from server.state import ServerState  # noqa: E402
from server.storage import delete_item, init_storage_db, save_item  # noqa: E402

FEATURE_PREFIX = "feat.stress-"
JOURNAL_PREFIX = "journal_stress-"


def build_state(config_path: str) -> ServerState:
    loader = ConfigLoader(Path(config_path))
    state = ServerState.from_loader(loader)
    init_storage_db(state)
    return state


def resolve_user(state: ServerState, username: str):
    user = get_user_by_username(state, username)
    if user:
        return user
    # Only ever creates the one conventional default-admin row (a no-op if
    # it already exists under a different username you passed) — this
    # script never invents a NEW user of its own.
    ensure_default_admin(state)
    user = get_user_by_username(state, username)
    if not user:
        raise SystemExit(
            f"No user '{username}' found, and the default admin uses a different username. "
            "Pass --username with a real account on this server."
        )
    return user


# Mirrors the real shape found in common/data/feature/*.json — enough fields
# that Vault/Crucible/Sanctum's own traversal (budgetCost, tags.categories,
# synergizesWith/conflictsWith) has real, structurally valid data to walk,
# not just enough to round-trip through save/list.
def build_feature(index: int) -> dict:
    id_ = f"{FEATURE_PREFIX}{index:05d}"
    return {
        "id": id_,
        "name": f"Stress Feature {index:05d}",
        "systemIds": ["sys.dnd5e"],
        "description": (
            f"Synthetic stress-test feature #{index:05d}, generated by "
            "server/scripts/stress_seed.py. Not real content."
        ),
        "mechanics": {"type": "passive", "text": "No real mechanical effect — stress-test data."},
        "budgetCost": (index % 5) + 1,
        "tags": {"categories": ["spell"] if index % 2 == 0 else ["item"]},
        # A handful of real cross-references (to OTHER synthetic ids, never
        # real content) so traversal has actual graph edges to walk, not an
        # empty list on every single node.
        "synergizesWith": [f"{FEATURE_PREFIX}{index - 1:05d}"] if index > 0 else [],
        "conflictsWith": [],
    }


def build_journal(index: int) -> dict:
    return {
        "title": f"Stress Journal {index:05d}",
        "body": (
            f"# Stress Journal {index:05d}\n\n"
            "Synthetic stress-test page, generated by server/scripts/stress_seed.py. "
            "Not real content.\n\n"
            f"Links to a neighbor for backlink testing: [[Stress Journal {max(0, index - 1):05d}]].\n"
        ),
        "tags": ["stress-test"],
        "refs": [],
    }


def seed(state: ServerState, user, kind: str, count: int) -> None:
    builder = build_feature if kind == "feature" else build_journal
    prefix = FEATURE_PREFIX if kind == "feature" else JOURNAL_PREFIX
    failures = 0
    for i in range(count):
        id_ = f"{prefix}{i:05d}"
        body = builder(i)
        try:
            save_item(state, kind, id_, body, user)
        except Exception as error:  # noqa: BLE001 — log and keep seeding
            failures += 1
            print(f"  ! failed to save {kind}/{id_}: {error}")
        if (i + 1) % 200 == 0 or i + 1 == count:
            print(f"  seeded {i + 1}/{count} {kind} records ({failures} failures so far)")
    print(f"Done: {count - failures}/{count} {kind} records seeded.")


def cleanup(state: ServerState, user, kind: str) -> None:
    prefix = FEATURE_PREFIX if kind == "feature" else JOURNAL_PREFIX
    rows = state.db.execute(
        "SELECT id FROM library_items WHERE kind = ? AND id LIKE ?",
        (kind, f"{prefix}%"),
    ).fetchall()
    if not rows:
        print(f"Nothing to clean up for {kind} (no ids matching '{prefix}*').")
        return
    removed = 0
    for row in rows:
        try:
            delete_item(state, kind, row["id"], user)
            removed += 1
        except Exception as error:  # noqa: BLE001 — log and keep cleaning up
            print(f"  ! failed to delete {kind}/{row['id']}: {error}")
    print(f"Removed {removed}/{len(rows)} synthetic {kind} records.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--config", default="server.config.json", help="Path to server configuration file")
    parser.add_argument("--kind", choices=["feature", "journal"], required=True)
    parser.add_argument("--count", type=int, default=500, help="How many synthetic records to seed")
    parser.add_argument("--username", default="admin", help="Owning account for seeded records")
    parser.add_argument("--cleanup", action="store_true", help="Remove synthetic records instead of creating them")
    args = parser.parse_args()

    if not Path(args.config).exists():
        raise SystemExit(f"Config file not found: {args.config} (run this from the repo root)")

    state = build_state(args.config)
    user = resolve_user(state, args.username)

    if args.cleanup:
        cleanup(state, user, args.kind)
    else:
        seed(state, user, args.kind, args.count)


if __name__ == "__main__":
    main()
